# Generated by Django 4.2 on 2023-04-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at']},
        ),
    ]
